name: Deploy NGINX to EKS

on:
  workflow_dispatch:  # manual trigger from GitHub UI

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
        aws-region: us-west-2

    - name: Set up kubeconfig
      run: |
        aws eks update-kubeconfig --region us-west-2 --name eks-spot-cluster-bibin

    - name: Deploy NGINX to EKS
      run: |
        kubectl create deployment nginx --image=nginx --port=80 --dry-run=client -o yaml | kubectl apply -f -
